import Foundation

// MARK: - API Check Result

enum APICheckResult: Equatable {
    case unchecked
    case checking
    case valid(latencyMs: Int)
    case invalid(message: String)

    var isValid: Bool {
        if case .valid = self { return true }
        return false
    }
}

// MARK: - AnthropicClient

final class AnthropicClient {
    let baseURL: String
    let authToken: String
    let model: String

    static let defaultModel = "claude-sonnet-4-20250514"

    static let revisePrompt = """
        You are a post-processor for voice-to-text transcripts generated by Whisper.

        Rules:
        1. If the transcript is empty or blank, respond with exactly nothing (empty response).
        2. Preserve the original meaning, tone, structure, and flow. Do NOT rewrite, summarize, expand, or change the speaker's intent.

        For NON-ENGLISH text (Chinese, Japanese, Korean, etc.):
        3. Add proper punctuation marks (，。！？、；：「」（）…).
        4. Fix obvious misheard words only when the correct word is unambiguous from context.
        5. Do NOT change grammar, word order, or sentence structure.

        For ENGLISH text:
        3. Fix spelling typos and speech recognition errors (e.g. "their" vs "there", "its" vs "it's").
        4. Fix grammar: subject-verb agreement, tense consistency, missing/extra articles (a/an/the), preposition errors.
        5. Add or fix punctuation (periods, commas, question marks, apostrophes).
        6. Fix word choice errors caused by speech recognition (e.g. homophones).
        7. Improve clarity only when the meaning is clearly implied by context; make the smallest possible correction.

        For MIXED-LANGUAGE text:
        Apply the appropriate rules to each language segment.

        CRITICAL: Your response must contain ONLY the corrected transcript text — nothing else. No explanations, no commentary, no preamble, no reasoning, no meta-discussion. If you cannot improve the text, return it exactly as-is.

        Transcript:

        """

    /// Validate that a base URL has a valid scheme (http or https).
    static func isValidBaseURL(_ urlString: String) -> Bool {
        guard !urlString.isEmpty else { return false }
        return urlString.hasPrefix("https://") || urlString.hasPrefix("http://")
    }

    /// Returns true if the URL uses plaintext HTTP to a non-localhost host.
    static func isInsecureURL(_ urlString: String) -> Bool {
        guard urlString.hasPrefix("http://") else { return false }
        let isLocalhost = urlString.hasPrefix("http://127.0.0.1") || urlString.hasPrefix("http://localhost")
        return !isLocalhost
    }

    init(baseURL: String, authToken: String, model: String = AnthropicClient.defaultModel) {
        self.baseURL = baseURL.hasSuffix("/") ? String(baseURL.dropLast()) : baseURL
        self.authToken = authToken
        self.model = model
    }

    /// Lightweight API check: send a tiny message and verify we get a valid response.
    func checkAPI(completion: @escaping (APICheckResult) -> Void) {
        let endpoint = "\(baseURL)/v1/messages"
        guard let url = URL(string: endpoint) else {
            completion(.invalid(message: "Invalid URL"))
            return
        }

        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue(authToken, forHTTPHeaderField: "x-api-key")
        request.setValue("2023-06-01", forHTTPHeaderField: "anthropic-version")
        request.timeoutInterval = 15

        let body: [String: Any] = [
            "model": model,
            "max_tokens": 1,
            "messages": [
                ["role": "user", "content": "hi"]
            ]
        ]
        request.httpBody = try? JSONSerialization.data(withJSONObject: body)

        let start = CFAbsoluteTimeGetCurrent()
        URLSession.shared.dataTask(with: request) { data, response, error in
            let latencyMs = Int((CFAbsoluteTimeGetCurrent() - start) * 1000)

            if let error {
                DispatchQueue.main.async {
                    completion(.invalid(message: error.localizedDescription))
                }
                return
            }

            let httpResponse = response as? HTTPURLResponse
            let statusCode = httpResponse?.statusCode ?? 0

            guard let data else {
                DispatchQueue.main.async {
                    completion(.invalid(message: "No data (HTTP \(statusCode))"))
                }
                return
            }

            DispatchQueue.main.async {
                switch statusCode {
                case 200:
                    completion(.valid(latencyMs: latencyMs))
                case 401, 403:
                    completion(.invalid(message: "Invalid API key or unauthorized"))
                case 404:
                    completion(.invalid(message: "Model not found or no access"))
                case 429:
                    completion(.invalid(message: "Rate limited, try again later"))
                case 500...599:
                    completion(.invalid(message: "Server error (HTTP \(statusCode))"))
                default:
                    let raw = String(data: data, encoding: .utf8) ?? ""
                    completion(.invalid(message: "HTTP \(statusCode): \(String(raw.prefix(100)))"))
                }
            }
        }.resume()
    }

    /// Send text through Claude for revision. Returns revised text or nil + error.
    /// If `prompt` is non-nil and non-empty, it is used instead of the default `revisePrompt`.
    func reviseText(_ text: String, prompt: String? = nil, completion: @escaping (String?, String?) -> Void) {
        let endpoint = "\(baseURL)/v1/messages"
        guard let url = URL(string: endpoint) else {
            completion(nil, "Invalid URL")
            return
        }

        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue(authToken, forHTTPHeaderField: "x-api-key")
        request.setValue("2023-06-01", forHTTPHeaderField: "anthropic-version")
        request.timeoutInterval = 30

        let effectivePrompt = (prompt?.isEmpty == false) ? prompt! : Self.revisePrompt
        // Ensure separator between prompt and text
        let fullContent = effectivePrompt.hasSuffix("\n") ? effectivePrompt + text : effectivePrompt + "\n\n" + text
        let body: [String: Any] = [
            "model": model,
            "max_tokens": 4096,
            "messages": [
                ["role": "user", "content": fullContent]
            ]
        ]
        request.httpBody = try? JSONSerialization.data(withJSONObject: body)

        URLSession.shared.dataTask(with: request) { data, response, error in
            if let error {
                DispatchQueue.main.async { completion(nil, "Network error: \(error.localizedDescription)") }
                return
            }

            let statusCode = (response as? HTTPURLResponse)?.statusCode ?? 0

            guard let data else {
                DispatchQueue.main.async { completion(nil, "No data (HTTP \(statusCode))") }
                return
            }

            guard let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
                let raw = String(data: data, encoding: .utf8) ?? "<binary>"
                DispatchQueue.main.async { completion(nil, "Invalid JSON (HTTP \(statusCode)): \(String(raw.prefix(200)))") }
                return
            }

            if let errorObj = json["error"] as? [String: Any],
               let message = errorObj["message"] as? String {
                DispatchQueue.main.async { completion(nil, "API error (HTTP \(statusCode)): \(message)") }
                return
            }

            guard let content = json["content"] as? [[String: Any]],
                  let firstBlock = content.first,
                  let text = firstBlock["text"] as? String
            else {
                DispatchQueue.main.async { completion(nil, "Unexpected response format (HTTP \(statusCode))") }
                return
            }

            DispatchQueue.main.async { completion(text.trimmingCharacters(in: .whitespacesAndNewlines), nil) }
        }.resume()
    }
}
